# Generated by Django 6.0.4 on 2026-04-07 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("area_especializacao", models.CharField(blank=True, max_length=200)),
                ("linkedin", models.URLField(blank=True)),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="docentes/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Licenciatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("regime", models.CharField(max_length=100)),
                ("ano_inicio", models.IntegerField()),
                ("ano_fim", models.IntegerField(blank=True, null=True)),
                ("ects", models.IntegerField()),
                ("media", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MakingOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entidade", models.CharField(max_length=100)),
                ("data", models.DateField(auto_now_add=True)),
                ("descricao", models.TextField()),
                ("erros", models.TextField(blank=True)),
                ("correcoes", models.TextField(blank=True)),
                (
                    "fotos",
                    models.ImageField(blank=True, null=True, upload_to="makingof/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("tipo", models.CharField(max_length=100)),
                ("categoria", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                (
                    "certificado",
                    models.FileField(blank=True, null=True, upload_to="certificados/"),
                ),
                ("carga_horaria", models.IntegerField(blank=True, null=True)),
                ("instituicao", models.CharField(max_length=200)),
                ("data_inicio", models.DateField(blank=True, null=True)),
                ("data_fim", models.DateField(blank=True, null=True)),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True, related_name="formacoes", to="portfolio.tecnologia"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("nivel", models.IntegerField()),
                ("descricao", models.TextField(blank=True)),
                ("tipo", models.CharField(max_length=100)),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True,
                        related_name="competencias",
                        to="portfolio.tecnologia",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("autor", models.CharField(blank=True, max_length=200)),
                ("ano", models.IntegerField()),
                ("classificacao", models.FloatField(blank=True, null=True)),
                ("relatorio", models.URLField(blank=True)),
                (
                    "licenciatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tfcs",
                        to="portfolio.licenciatura",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UnidadeCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("avaliacao", models.TextField(blank=True)),
                ("dificuldade", models.CharField(blank=True, max_length=100)),
                ("semestre", models.IntegerField()),
                ("ano_curricular", models.IntegerField()),
                (
                    "docentes",
                    models.ManyToManyField(
                        blank=True, related_name="ucs", to="portfolio.docente"
                    ),
                ),
                (
                    "licenciatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ucs",
                        to="portfolio.licenciatura",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("descricao", models.TextField(blank=True)),
                ("data_inicio", models.DateField(blank=True, null=True)),
                ("data_fim", models.DateField(blank=True, null=True)),
                ("link_github", models.URLField(blank=True)),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True, related_name="projetos", to="portfolio.tecnologia"
                    ),
                ),
                (
                    "uc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projetos",
                        to="portfolio.unidadecurricular",
                    ),
                ),
            ],
        ),
    ]
