# Generated by Django 6.0.4 on 2026-04-07 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="competencia",
            options={"verbose_name_plural": "Competências"},
        ),
        migrations.AlterModelOptions(
            name="docente",
            options={"ordering": ["nome"], "verbose_name_plural": "Docentes"},
        ),
        migrations.AlterModelOptions(
            name="formacao",
            options={"verbose_name_plural": "Formações"},
        ),
        migrations.AlterModelOptions(
            name="licenciatura",
            options={"verbose_name_plural": "Licenciaturas"},
        ),
        migrations.AlterModelOptions(
            name="makingof",
            options={
                "ordering": ["-data"],
                "verbose_name": "Making Of",
                "verbose_name_plural": "Making Of",
            },
        ),
        migrations.AlterModelOptions(
            name="projeto",
            options={"verbose_name_plural": "Projetos"},
        ),
        migrations.AlterModelOptions(
            name="tecnologia",
            options={"verbose_name_plural": "Tecnologias"},
        ),
        migrations.AlterModelOptions(
            name="tfc",
            options={"verbose_name_plural": "TFCs"},
        ),
        migrations.AlterModelOptions(
            name="unidadecurricular",
            options={"verbose_name_plural": "Unidades Curriculares"},
        ),
        migrations.AddField(
            model_name="projeto",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="projetos/"),
        ),
        migrations.AddField(
            model_name="projeto",
            name="video",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="tecnologia",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="tecnologias/"),
        ),
        migrations.AddField(
            model_name="tecnologia",
            name="preferencia",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tecnologia",
            name="url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="ucs/"),
        ),
        migrations.AlterField(
            model_name="competencia",
            name="tipo",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="formacao",
            name="instituicao",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="licenciatura",
            name="ects",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="licenciatura",
            name="regime",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="makingof",
            name="descricao",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="makingof",
            name="entidade",
            field=models.CharField(
                choices=[
                    ("licenciatura", "Licenciatura"),
                    ("uc", "Unidade Curricular"),
                    ("docente", "Docente"),
                    ("projeto", "Projeto"),
                    ("tecnologia", "Tecnologia"),
                    ("tfc", "TFC"),
                    ("competencia", "Competência"),
                    ("formacao", "Formação"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="tecnologia",
            name="categoria",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="tecnologia",
            name="tipo",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="classificacao",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Insuficiente"),
                    (2, "Suficiente"),
                    (3, "Bom"),
                    (4, "Muito Bom"),
                    (5, "Perfeito"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="titulo",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="dificuldade",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
