# Generated by Django 6.0.4 on 2026-04-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_alter_competencia_options_alter_docente_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tfc",
            old_name="classificacao",
            new_name="rating",
        ),
        migrations.RemoveField(
            model_name="tfc",
            name="ano",
        ),
        migrations.RemoveField(
            model_name="tfc",
            name="relatorio",
        ),
        migrations.AddField(
            model_name="tfc",
            name="areas",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="tfc",
            name="curso",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="tfc",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="tfc",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="tfcs/"),
        ),
        migrations.AddField(
            model_name="tfc",
            name="orientador",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="tfc",
            name="palavras_chave",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="tfc",
            name="resumo",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="tecnologias",
            field=models.ManyToManyField(
                blank=True, related_name="tfcs", to="portfolio.tecnologia"
            ),
        ),
    ]
