# Generated by Django 6.0.4 on 2026-04-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_rename_classificacao_tfc_rating_remove_tfc_ano_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tfc",
            name="areas",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
