# Generated by Django 6.0.4 on 2026-04-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_alter_tfc_areas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tfc",
            name="palavras_chave",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
