# Generated by Django 6.0.4 on 2026-04-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_unidadecurricular_bibliografia_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="licenciatura",
            name="ects",
        ),
        migrations.RemoveField(
            model_name="licenciatura",
            name="media",
        ),
        migrations.AddField(
            model_name="licenciatura",
            name="descricao",
            field=models.TextField(blank=True),
        ),
    ]
