# Generated by Django 6.0.4 on 2026-04-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio",
            "0007_remove_licenciatura_ects_remove_licenciatura_media_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="licenciatura",
            name="descricao",
        ),
        migrations.AddField(
            model_name="licenciatura",
            name="ects",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="licenciatura",
            name="media",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
