# Generated by Django 6.0.4 on 2026-04-09 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0008_remove_licenciatura_descricao_licenciatura_ects_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="unidadecurricular",
            options={
                "ordering": ["ano_curricular", "semestre", "nome"],
                "verbose_name_plural": "Unidades Curriculares",
            },
        ),
        migrations.RenameField(
            model_name="unidadecurricular",
            old_name="dificuldade",
            new_name="cod_curso",
        ),
        migrations.RemoveField(
            model_name="unidadecurricular",
            name="avaliacao",
        ),
        migrations.RemoveField(
            model_name="unidadecurricular",
            name="foto",
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="cod_uc",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="ects",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
