# Generated by Django 6.0.4 on 2026-04-09 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0009_alter_unidadecurricular_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="licenciatura",
            name="media",
        ),
        migrations.AddField(
            model_name="licenciatura",
            name="descricao",
            field=models.TextField(blank=True),
        ),
    ]
