# Generated by Django 6.0.4 on 2026-04-09 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0010_remove_licenciatura_media_licenciatura_descricao"),
    ]

    operations = [
        migrations.RenameField(
            model_name="unidadecurricular",
            old_name="descricao",
            new_name="apresentacao",
        ),
    ]
