# Generated by Django 6.0.4 on 2026-04-09 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0011_rename_descricao_unidadecurricular_apresentacao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tfc",
            name="orientador",
        ),
        migrations.AddField(
            model_name="tfc",
            name="orientador",
            field=models.ManyToManyField(blank=True, to="portfolio.docente"),
        ),
    ]
