# Generated by Django 6.0.4 on 2026-04-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0012_remove_tfc_orientador_tfc_orientador"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projeto",
            name="video",
            field=models.URLField(blank=True, null=True),
        ),
    ]
