# Generated by Django 6.0.4 on 2026-04-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0013_alter_projeto_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="makingof",
            name="documento",
            field=models.FileField(blank=True, null=True, upload_to="makingof/docs/"),
        ),
    ]
