# Generated by Django 6.0.4 on 2026-05-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0014_makingof_documento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docente",
            name="nome",
            field=models.TextField(max_length=200),
        ),
    ]
