# Generated by Django 6.0.4 on 2026-05-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0015_alter_docente_nome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tfc",
            name="areas",
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="palavras_chave",
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="titulo",
            field=models.TextField(max_length=300),
        ),
    ]
