# Generated by Django 6.0.4 on 2026-05-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0016_alter_tfc_areas_alter_tfc_palavras_chave_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competencia",
            name="nome",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="competencia",
            name="tipo",
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="docente",
            name="area_especializacao",
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="formacao",
            name="instituicao",
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="formacao",
            name="nome",
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name="licenciatura",
            name="nome",
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name="licenciatura",
            name="regime",
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="makingof",
            name="entidade",
            field=models.TextField(
                choices=[
                    ("licenciatura", "Licenciatura"),
                    ("uc", "Unidade Curricular"),
                    ("docente", "Docente"),
                    ("projeto", "Projeto"),
                    ("tecnologia", "Tecnologia"),
                    ("tfc", "TFC"),
                    ("competencia", "Competência"),
                    ("formacao", "Formação"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="nome",
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name="tecnologia",
            name="categoria",
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="tecnologia",
            name="nome",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="tecnologia",
            name="tipo",
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="autor",
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="curso",
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="natureza",
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="nome",
            field=models.TextField(max_length=200),
        ),
    ]
